fix: create empty array of options if undefined
pmsipilot/jenklab-ci pull request #9
Opened 2017-05-05 10:15 UTC by desaintvincent

create an empty array if there is no options to prevent crash.

close #8

2017-05-05 12:19 UTC, wixyvir commented on src/index.js
> +            let optionsParameter = [];
Why not a simple conditional ternary operator?

2017-05-05 12:57 UTC, desaintvincent commented on src/index.js
> +            let optionsParameter = [];
done

2017-05-05 12:59 UTC, wixyvir commented
:+1:

2017-05-09 08:10 UTC, jubianchi requested changes

2017-05-09 08:10 UTC, jubianchi commented on src/index.js
> +            buildJobRequest(args.job, options.parameter === undefined ? [] :
ˋ(options.parameter || []).map(...)`

2017-05-15 15:32 UTC, jubianchi approved these changes

2017-05-15 15:36 UTC, jubianchi commented
Closed in favor of #10

2017-05-15 15:36 UTC, closed without merging